[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "astroponterr"
version = "0.0.0"
authors = [
    {name = "Huntington Gazecki", email = 'gazecki.hunt@gmail.com'}
]
maintainers = [
    {name = "Huntington Gazecki", email = 'gazecki.hunt@gmail.com'}
]
description = "digital sextant"
readme = {file = "readme.md", content-type = "text/markdown"}
license = "MIT AND (Apache-2.0 OR BSD-2-Clause)" 
requires-python = ">= 3.13"

dependencies = [
    "numpy",
    "scipy",
    "skyfield",
    "opencv-python", # needed?
    "polars",
    "astropy",
    "astrometry", # using python interface for now
]


[project.optional-dependencies]
all = [
    "astroponterr[dev]",
    "astroponterr[gui]",
]
dev = [
    "pre-commit",
    "ruff",
    "uv",
    "ipython",
    "ipdb",
    "jupyter"
]
gui = [
    "matplotlib",
    "seaborn",
    "pyqt6",
    #"altair",
]
